name: boilerplate_mux
description: Boilerplate application for Jaguar with a sample HTTP server using mux
version: 2.4.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar: ^2.4.4
  jaguar_resty: ^2.8.0

dev_dependencies:
  test: ^1.3.0
