name: boilerplate_mux
description: Boilerplate for jaguar_mux
version: 2.2.0
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar: ^2.2.0
  jaguar_resty: ^2.6.2

dev_dependencies:
  test: ^1.3.0
