name: boilerplate_mux
description: Boilerplate for jaguar_mux
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  jaguar_mux: '>=0.4.0 <0.5.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
