name: boilerplate_mux
description: Boilerplate for jaguar_mux
version: 2.1.8

environment:
  sdk: ">=1.20.0 <2.0.0"

dependencies:
  jaguar: ^2.1.8
  jaguar_resty: ^2.5.5

dev_dependencies:
  test: ^1.0.0
