name: boilerplate_mux
description: Boilerplate for jaguar_mux
version: 0.5.0

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  jaguar: '>=0.5.3 <0.6.0'
  jaguar_mux: '>=0.5.0 <0.6.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
